
var btninfoimg=document.getElementById("info_img");

var infotxt=document.getElementById("info_txt");
var infocolumn=document.getElementById("info-column");

btninfoimg.addEventListener('click', function(){
	infotxt.classList.toggle('mostrar_info');
	infocolumn.classList.toggle("transicion");
})


/*----------------------------------*/

var btninfoimg1=document.getElementById("info_img1");

var infotxt1=document.getElementById("info_txt1");
var infocolumn1=document.getElementById("info-column1");

btninfoimg1.addEventListener('click', function(){
	infotxt1.classList.toggle('mostrar_info');
	infocolumn1.classList.toggle("transicion");
})

/*-----------------------------------------------*/

var btninfoimg2=document.getElementById("info_img2");

var infotxt2=document.getElementById("info_txt2");
var infocolumn2=document.getElementById("info-column2");

btninfoimg2.addEventListener('click', function(){
	infotxt2.classList.toggle('mostrar_info');
	infocolumn2.classList.toggle("transicion");
})

/*-------------------------------------------*/

var btninfoimg3=document.getElementById("info_img3");

var infotxt3=document.getElementById("info_txt3");
var infocolumn3=document.getElementById("info-column3");
btninfoimg3.addEventListener('click', function(){
	infotxt3.classList.toggle('mostrar_info');
	infocolumn3.classList.toggle("transicion");
})

/*------------------------------------------------*/
/*--------------------------------------------------*/
/*--------------------------------------------------------*/

var btntitulo=document.getElementById("btn-info-titulo")

btntitulo.addEventListener('click', function(){
	infotxt.classList.toggle('mostrar_info');
	infocolumn.classList.toggle("transicion");
})

/*----------------------------*/

var btntitulo1=document.getElementById("btn-info-titulo1")

btntitulo1.addEventListener('click', function(){
	infotxt1.classList.toggle('mostrar_info');
	infocolumn1.classList.toggle("transicion");
})

/*--------2*/

var btntitulo2=document.getElementById("btn-info-titulo2")

btntitulo2.addEventListener('click', function(){
	infotxt2.classList.toggle('mostrar_info');
	infocolumn2.classList.toggle("transicion");
})

/*-----3*/

var btntitulo3=document.getElementById("btn-info-titulo3")

btntitulo3.addEventListener('click', function(){
	infotxt3.classList.toggle('mostrar_info');
	infocolumn3.classList.toggle("transicion");
})